### ISSUE TITLE
Why use retain_graph?

### ISSUE THREAD

**Issue by viyjy** [ChandlerBang/pytorch-gnn-meta-attack#1]
Hi, I was wondering why set retain_graph=True in this [line](https://github.com/ChandlerBang/pytorch-gnn-meta-attack/blob/734249700a0b4d987540f5b2207c85668f3c69b3/metattack.py#L216). Actually, retain_graph=True/False makes no differences to the result. Thanks.

**Comment by ChandlerBang** [comment]
Hi, you are right.  According to pytorch documentation, `retain_graph` will retain the computation graph for calculating gradient.

```retain_graph (bool, optional) – If False, the graph used to compute the grad will be freed. Note that in nearly all cases setting this option to True is not needed and often can be worked around in a much more efficient way. Defaults to the value of create_graph.```

For line 216, there is no need to maintain the computation graph since it is in the outer training stage. For other lines containing `retain_graph=True`,  I think we need  to keep it.

**Comment by viyjy** [comment]
Thanks for your information.
